### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by aaaholding** [ilya-lesikov/gke-demo#5]
@ilya-lesikov nice work

is it possible to use Jenkins in a docker container to build the app instead of GCP Code deploy?

Can you please create an example with Jenkins running in docker for building artifacts? 

Thanks

**Comment by ilya-lesikov** [comment]
Hi, sorry for late answer. Potentially you can use anything instead of GCP Cloud Build, be it Jenkins, GitHub Actions or whatever. I'm working full-time right now and don't have the capacity to redo that for Jenkins. It shouldn't be that much work though, if you don't dig much into Groovy and all that and stick to the plain shell, then half of the work is just copypasting shell instructions from cloudbuild.yml to your Jenkins pipeline.
